# Generated by Django 2.2 on 2019-10-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(upload_to='Tarea3/TareaG11prim/app/img/'),
        ),
    ]
