# Generated by Django 2.2 on 2019-10-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191017_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
