# Generated by Django 2.2 on 2019-10-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191017_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='descripcion',
            new_name='mensaje',
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='foto',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
