# Generated by Django 2.2 on 2019-10-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191017_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='foto',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
