# Generated by Django 2.2 on 2019-10-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191018_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='contexto',
        ),
        migrations.AddField(
            model_name='carro',
            name='productos',
            field=models.ManyToManyField(blank=True, to='app.Productos'),
        ),
    ]
