# Generated by Django 2.2 on 2019-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191018_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
