# Generated by Django 2.2 on 2019-10-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pedidos_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
